const Log = require('../src/Log')
//FLogs.log('Hex white', 't', '#ccc')
// FLogs.log('Hex white')
//      .text('new text')
//      .textColor('#ccc')
//      .label('t')
//      .labelColor('#ccc')
//      .prefix('p')
//      .prefixColor('#ccc')
//      .timeStampStruct('HH:mm:ss')
//      .timeStampColor('#ccc')

// new Log().message('new text')
//      .messageColor('#ccc')
//      .label('t')
//      .labelColor('#ccc')
//      .prefix('p')
//      .prefixColor('#ccc')
//      .timeStampStruct('HH:mm:ss')
//      .timeStampColor('#ccc')

new Log().message('test')
         .label('t')
         .labelColor('red')
         .log()


new Log().message('test')
    .prefix('p')
    .prefixColor('pink')
    .label('t')
    .labelColor('red')
    .log()

new Log().message('test')
    .prefix('p')
    .prefixColor('pink')
    .label('t')
    .labelColor('red')
    .timeStampColor('blue')
    .log()

new Log().message('test')
    .prefix('p')
    .prefixColor('pink')
    .label(['t', 'y'])
    .labelColor('red')
    .timeStampColor('blue')
    .log()


new Log().message('test')
    .prefix('p')
    .prefixColor('pink')
    .label(['t', 'y'])
    .labelColor(['red', 'white'])
    .timeStampColor('blue')
    .log()

new Log().message()
    .prefix('p')
    .prefixColor('green')
    .label(['t', 'y'], ['red', 'brown'])
    .log('Hello!')

new Log().message()
    .prefix('p')
    .prefixColor('green')
    .label(['t', 'y'], ['red', 'brown'])
    .noTimeStamp()
    .log('Hello!')

new Log().log('hey')
new Log().noTimeStamp().log('hey')
new Log({timeStamp: false}).log('false')